name: Crownqltechn
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: haifu5872/crownqltechn@dependabot-github_actions
      with:
          kernel-url: https://github.com/klabit87/android_kernel_samsung_sdm845
          kernel-dir: sdm845
          kernel-branch: pie
          config: sdm845_sec_defconfig_five
          arch: arm64
          gcc64-tar: https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
          path: $HOME/gcc64/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu/bin:$PATH
          cflags: "CROSS_COMPILE=aarch64-none-linux-gnu-"
          python: python2
          anykernel3: true
          extra-version: -klabit
